apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: minio
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: picture-dep
      eventSourceName: minio
      eventName: picture
    - name: json-dep
      eventSourceName: minio
      eventName: json
  triggers:
    - template:
        name: minio-picture-trigger
        conditions: "picture-dep"
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: arguments-parameters-
              spec:
                entrypoint: main

                arguments:
                  parameters:
                  - name: path
                    value: input.jpg

                templates:
                - name: main
                  steps:
                  - - name: find-faces
                      template: find-faces
                      arguments:
                        parameters:
                        - name: path
                          value: "{{workflow.parameters.path}}"

                  - - name: upload-result
                      template: upload-result
                      arguments:
                        artifacts:
                        - name: file
                          from: "{{steps.find-faces.outputs.artifacts.photo}}"
                      

                - name: find-faces
                  inputs:
                    parameters:
                    - name: path
                    artifacts:
                    - name: photo
                      path: /photo.jpg
                      s3:
                        endpoint: kubecon-demo-minio:9000
                        insecure: true
                        bucket: kubecon-demo
                        key: "{{inputs.parameters.path}}"
                        accessKeySecret:
                          name: kubecon-demo-minio
                          key: accesskey
                        secretKeySecret:
                          name: kubecon-demo-minio
                          key: secretkey
                  container:
                    image: alexmt/facedetect
                    command: [python]
                    args: ["/app/facedetect", "-o", "/result.jpg", "photo.jpg"]
                  outputs:
                    artifacts:
                    - name: photo
                      path: "/result.jpg"

                - name: upload-result
                  inputs:
                    artifacts:
                    - name: file
                      path: /tmp/file
                  container:
                    env:
                    - name: AWS_ACCESS_KEY_ID
                      valueFrom:
                        secretKeyRef:
                          name: kubecon-demo-minio
                          key: accesskey
                    - name: AWS_SECRET_ACCESS_KEY
                      valueFrom:
                        secretKeyRef:
                          name: kubecon-demo-minio
                          key: secretkey
                    image: amazon/aws-cli
                    command: [aws]
                    args: ["--endpoint-url", "http://kubecon-demo-minio:9000/", "s3", "cp", "/tmp/file", "s3://kubecon-demo/{{workflow.parameters.path}}.png"]
          # The container args from the workflow are overridden by the s3 notification key
          parameters:
            - src:
                dependencyName: picture-dep
                dataKey: notification.0.s3.object.key
              dest: spec.arguments.parameters.0.value

    - template:
        name: minio-json-trigger
        conditions: "json-dep"
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: process-raw-log-
              spec:
                entrypoint: process-raw-log
                arguments:
                  parameters:
                  - name: path
                    value: input.json
                templates:
                  - name: process-raw-log
                    steps:
                    - - name: next-step
                        template: next-step
                        arguments:
                          parameters:
                          - name: path
                            value: "{{workflow.parameters.path}}"
                    - - name: form
                        template: form                 
                        when: "{{steps.next-step.outputs.parameters.rst}} == form"
                      - name: lp5
                        template: lp5                
                        when: "{{steps.next-step.outputs.parameters.rst}} == lp5"
                  
                  - name: next-step
                    parameters:
                      - name: path
                    artifacts:
                    - name: rawlog
                      path: /rawlog.json
                      s3:
                        endpoint: kubecon-demo-minio:9000
                        insecure: true
                        bucket: kubecon-demo
                        key: "{{inputs.parameters.path}}"
                        accessKeySecret:
                          name: kubecon-demo-minio
                          key: accesskey
                        secretKeySecret:
                          name: kubecon-demo-minio
                          key: secretkey

                    container:
                      image: python_next_step:0.4
                      command: [python]
                      args: ["/app/next_step.py", "/rawlog.json"]  # generate the content of hello_world.txt
                      imagePullPolicy: IfNotPresent
                    outputs:
                      parameters:
                      - name: rst      # name of output parameter
                        valueFrom:
                          path: /out.txt    # set the value of hello-param to the contents of this hello-world.txt

                  - name: form
                    container:
                      image: alpine:3.6
                      command: [sh, -c]
                      args: ["echo \"processing form\""]

                  - name: lp5
                    container:
                      image: alpine:3.6
                      command: [sh, -c]
                      args: ["echo \"processing lp5\""]
          parameters:
            - src:
                dependencyName: json-dep
                dataKey: notification.0.s3.object.key
              dest: spec.arguments.parameters.0.value
